### PR TITLE
[KEYCLOAK-8652] Rebase RH-SSO 7.3 TP CD standalone image on top of EAP CD 14.0 image

### PR DESCRIPTION
**Pull request by iankko**
_Note:_ The version of the Keycloak server overlay archive to be updated yet, once upstream _4.6.0.Final_ server overlay archive version is available. See the corresponding JIRA for the availability of the testing image.

Signed-off-by: Jan Lieskovsky <jlieskov@redhat.com>

Thanks for submitting your Pull Request!

Please make sure your PR meets the following requirements:

- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for other issues
- [ ] Attached commits represent units of work and are properly formatted
- [ ] You have read and agreed to the Developer Certificate of Origin (DCO) (see `CONTRIBUTING.md`)
- [ ] Every commit contains `Signed-off-by: Your Name <yourname@example.com>` - use `git commit -s`

### CODE REVIEW

**Comment by iankko** [comment]
@luck3y @rcernich @Crumby @pdrozd PTAL (once got a chance)

Thank you, Jan

**Comment by Crumby** [comment]
@iankko LGTM

**Comment by iankko** [comment]
@Crumby Thanks, Pavel! Actually looks, updated Keycloak server overlay should be available soon (ETA ~hours), thus will update this one with the new md5/sha sum once available.

**Review by luck3y — APPROVED** [review]

**Comment by iankko** [comment]
This one should be ready to go (exact Keycloak server overlay version doesn't need to be referenced per @goldmann )

@ASzc PTAL (once got a chance)

Thanks, Jan

**Comment by iankko** [comment]
Actually merging this, so we can rebuild.

**Pull request merged**
