### PR TITLE
[KEYCLOAK-12837] Explicitly perform a system update (update packages having available security errata) as part of image build

### PR DESCRIPTION
**Pull request by iankko**
[KEYCLOAK-12837] Explicitly perform a system update
    (only install the packages that have a security errata)
    as part of the RH-SSO standalone image build
    
    Signed-off-by: Jan Lieskovsky <jlieskov@redhat.com>

Thanks for submitting your Pull Request!

Please make sure your PR meets the following requirements:

- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for other issues
- [ ] Attached commits represent units of work and are properly formatted
- [ ] You have read and agreed to the Developer Certificate of Origin (DCO) (see `CONTRIBUTING.md`)
- [ ] Every commit contains `Signed-off-by: Your Name <yourname@example.com>` - use `git commit -s`

### CODE REVIEW

**Comment by iankko** [comment]
@hmlnarik @drichtarik PTAL once got a chance

Thanks!, Jan

**Comment by iankko** [comment]
JFTR, tried to build the image locally (with CEKIT 3.6.0 -- `cekit-3.6.0-1.el7.noarch`) & it works & contains the most recent security updates:
```
...
2020-01-30 12:40:33,765 cekit        INFO     Docker: Successfully built 628db148f03b
2020-01-30 12:40:33,815 cekit        INFO     Squashing image 628db148f03b...
2020-01-30 12:40:33,823 cekit        INFO     docker-squash version 1.0.7, Docker 4ef4b30/1.13.1, API 1.26...
2020-01-30 12:40:33,823 cekit        INFO     Using v2 image format
...
2020-01-30 12:44:51,344 cekit        INFO     Squashing finished!
2020-01-30 12:44:54,271 cekit        DEBUG    Moving unmodified layer '5cb5b345d95947082b4c2ef8299c55730dcad42b5615fd9a4b4a92ba19015399'...
2020-01-30 12:44:54,271 cekit        DEBUG    Moving unmodified layer '21f0a0a5e8ed9b2b40e26f53549fb99b688816c46f43a4cae8f01267aa8d427b'...
2020-01-30 12:44:54,271 cekit        DEBUG    No name and tag provided for the image, skipping generating repositories file
2020-01-30 12:44:54,272 cekit        DEBUG    Removing from disk already squashed layers...
2020-01-30 12:44:54,353 cekit        INFO     Original image size: 3058.93 MB
2020-01-30 12:44:54,353 cekit        INFO     Squashed image size: 827.10 MB
2020-01-30 12:44:54,353 cekit        INFO     Image size decreased by 72.96 %
2020-01-30 12:44:54,353 cekit        INFO     New squashed image ID is 8dbba0b5e9cf7a9544266dfe88c3ab53e6c5cbd9075373e11e4560b81bce1563
2020-01-30 12:44:54,353 cekit        DEBUG    Generating tar archive for the squashed image...
2020-01-30 12:45:05,320 cekit        DEBUG    Archive generated
2020-01-30 12:45:05,321 cekit        DEBUG    Loading squashed image...
2020-01-30 12:46:26,183 cekit        DEBUG    Image loaded!
2020-01-30 12:46:26,200 cekit        DEBUG    Cleaning up /tmp/docker-squash-J0mlhc temporary directory
2020-01-30 12:46:26,266 cekit        INFO     Removing old 628db148f03b image...
2020-01-30 12:46:27,614 cekit        INFO     Image removed!
2020-01-30 12:46:27,614 cekit        INFO     Done
2020-01-30 12:46:27,882 cekit        INFO     Image built and available under following tags: redhat-sso-7/sso73:7.3.6.GA, redhat-sso-7/sso73:latest
2020-01-30 12:46:27,882 cekit        INFO     Finished!
...
```

**Comment by iankko** [comment]
_Update:_
It's not a blocker anymore (see the corresponding thread). But still would be good to get this change in IMHO, so we have second level of check to catch (the possible future case), when the base image doesn't have all the available updates installed.

**Review by hmlnarik — APPROVED** [review]
This version looks good to me, thanks!

**Comment by iankko** [comment]
Verified, the change works correctly in both:
- Local docker image build scenario:
```
...
020-01-31 13:27:33,959 cekit        INFO     Docker: Removing intermediate container 58a8cf48d510
2020-01-31 13:27:33,959 cekit        INFO     Docker: Step 6/56 : RUN sh -x /tmp/scripts/base.image.security.errata.update/perform.sh
2020-01-31 13:27:34,010 cekit        INFO     Docker: ---> Running in 23695bb94705
2020-01-31 13:27:34,012 cekit        INFO     Docker: 
2020-01-31 13:27:34,389 cekit        INFO     Docker: + set -eu
2020-01-31 13:27:34,389 cekit        INFO     Docker: + echo 'Updating packages that have a security errata available'
2020-01-31 13:27:34,389 cekit        INFO     Docker: + yum update-minimal --security -y
2020-01-31 13:27:34,392 cekit        INFO     Docker: Updating packages that have a security errata available
...
2020-01-31 13:28:38,591 cekit        INFO     Docker: Resolving Dependencies
2020-01-31 13:28:38,591 cekit        INFO     Docker: --> Running transaction check
2020-01-31 13:28:38,591 cekit        INFO     Docker: ---> Package nss.x86_64 0:3.44.0-4.el7 will be updated
2020-01-31 13:28:38,596 cekit        INFO     Docker: ---> Package nss.x86_64 0:3.44.0-7.el7_7 will be an update
2020-01-31 13:28:38,612 cekit        INFO     Docker: ---> Package nss-softokn.x86_64 0:3.44.0-5.el7 will be updated
2020-01-31 13:28:38,612 cekit        INFO     Docker: ---> Package nss-softokn.x86_64 0:3.44.0-8.el7_7 will be an update
2020-01-31 13:28:38,621 cekit        INFO     Docker: ---> Package nss-softokn-freebl.x86_64 0:3.44.0-5.el7 will be updated
2020-01-31 13:28:38,621 cekit        INFO     Docker: ---> Package nss-softokn-freebl.x86_64 0:3.44.0-8.el7_7 will be an update
2020-01-31 13:28:38,621 cekit        INFO     Docker: ---> Package nss-sysinit.x86_64 0:3.44.0-4.el7 will be updated
2020-01-31 13:28:38,622 cekit        INFO     Docker: ---> Package nss-sysinit.x86_64 0:3.44.0-7.el7_7 will be an update
2020-01-31 13:28:38,624 cekit        INFO     Docker: ---> Package nss-tools.x86_64 0:3.44.0-4.el7 will be updated
2020-01-31 13:28:38,624 cekit        INFO     Docker: ---> Package nss-tools.x86_64 0:3.44.0-7.el7_7 will be an update
2020-01-31 13:28:38,639 cekit        INFO     Docker: ---> Package nss-util.x86_64 0:3.44.0-3.el7 will be updated
2020-01-31 13:28:38,643 cekit        INFO     Docker: ---> Package nss-util.x86_64 0:3.44.0-4.el7_7 will be an update
2020-01-31 13:28:38,643 cekit        INFO     Docker: ---> Package sqlite.x86_64 0:3.7.17-8.el7 will be updated
2020-01-31 13:28:38,643 cekit        INFO     Docker: ---> Package sqlite.x86_64 0:3.7.17-8.el7_7.1 will be an update
2020-01-31 13:28:38,691 cekit        INFO     Docker: --> Finished Dependency Resolution
...
```
- And also in OSBS build scenario (taskId = 26156215):
```
...
2020-01-31 13:11:58,915 - ... - DEBUG - Updating packages that have a security errata available
2020-01-31 13:11:58,915 - ... - DEBUG - [91m+ yum update-minimal --security -y
2020-01-31 13:11:58,915 - ... - DEBUG - [0m
...
2020-01-31 13:12:16,920 - ... - DEBUG - No Packages marked for minimal Update
...
```

For both of the scenarios above, got the latest updated packages (having security errata) available.

**Comment by iankko** [comment]
Merging based on the testing result above. @hmlnarik Thanks for the review!

**Pull request merged**
