### PR TITLE
[Post 7.2.4.GA -cp to -dev sync] Update to EAP 7.1.4-1. Update to RH-SSO 7.2.4.CR2.

### PR DESCRIPTION
**Pull request by iankko**
Signed-off-by: Jan Lieskovsky <jlieskov@redhat.com>

Thanks for submitting your Pull Request!

Please make sure your PR meets the following requirements:

- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for other issues
- [ ] Attached commits represent units of work and are properly formatted
- [ ] You have read and agreed to the Developer Certificate of Origin (DCO) (see `CONTRIBUTING.md`)
- [ ] Every commit contains `Signed-off-by: Your Name <yourname@example.com>` - use `git commit -s`

### CODE REVIEW

**Comment by iankko** [comment]
@goldmann @rcernich @ASzc @pskopek PTAL (once got a chance)

Thank you, Jan

**Review by rcernich — APPROVED** [review]
LGTM.  Did you want to merge a single commit between branches, e.g. merge -dev into -cp or vice versa?

**Comment by iankko** [comment]
@rcernich Thanks for the review, Rob!

Ad single commit merge - how do I do that? Merge of whole differences between the branches (e.g. `sso72-cp` to `sso72`) doesn't seem to be possible already, since there are some override-cp changes in `sso72-cp` branch, which wouldn't apply to release branch).

But merging a single commits might work. Did you mean something like this: https://gist.github.com/unbracketed/889c844473bcca1917e2 ?

**Comment by rcernich** [comment]
@iankko, sorry, i just meant merge it into one branch, then merge those branches when the time comes, e.g. merge it into the release branch, then merge the release branch into -dev and -cp.  Cherry-picking should work too, as those should allow you to merge branches with like commits without issues.  Merging different commits with the same changes into separate branches will cause issues later if you ever want to merge those branches, e.g. -dev into -cp, etc.

**Review by pskopek — COMMENTED** [review]
Looks good to me.

**Comment by iankko** [comment]
@pskopek Thanks for the review, Peter!

**Pull request merged**
