### PR TITLE
[WIP] [DNM] [KEYCLOAK-12850] Change the pull specification of the base image to the externally accessible one

### PR DESCRIPTION
**Pull request by iankko**
[KEYCLOAK-12850] Change the pull specification of the base
    image to the externally accessible one
    
    Signed-off-by: Jan Lieskovsky <jlieskov@redhat.com>

See the relevant JIRA description for explanation, why it's necessary.

Thanks for submitting your Pull Request!

Please make sure your PR meets the following requirements:

- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for other issues
- [ ] Attached commits represent units of work and are properly formatted
- [ ] You have read and agreed to the Developer Certificate of Origin (DCO) (see `CONTRIBUTING.md`)
- [ ] Every commit contains `Signed-off-by: Your Name <yourname@example.com>` - use `git commit -s`

### CODE REVIEW

**Comment by iankko** [comment]
@hmlnarik @drichtarik PTAL once got a chance

Thanks! Jan

**Review by hmlnarik — CHANGES_REQUESTED** [review]
I am not convinced this is the correct approach. Would #106 work instead?

**Comment by iankko** [comment]
> I am not convinced this is the correct approach. Would #106 work instead?

As discussed previously on the chat, will explore that possibility further yet & report results back. Thanks for catching this! (agree with you, better not to diverge from the current pull spec if possible).

**Comment by iankko** [comment]
Closing as WONTFIX (https://github.com/jboss-container-images/redhat-sso-7-image/pull/106 one was done instead).

**Pull request closed without merging**
